# Generated by Django 4.0.1 on 2022-01-12 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('state', models.SmallIntegerField(choices=[(-1, 'Deleted'), (0, 'Paused'), (1, 'Active'), (2, 'For Review'), (3, 'Expired'), (4, 'Cancelled'), (5, 'Signal Delete on adword and local'), (6, 'Signal Pause on adword and local'), (7, 'Signal Active on adword and local'), (8, 'STRATEGY KEYWORD SYNONMYS')], default=1, verbose_name='Publish state')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('state', models.SmallIntegerField(choices=[(-1, 'Deleted'), (0, 'Paused'), (1, 'Active'), (2, 'For Review'), (3, 'Expired'), (4, 'Cancelled'), (5, 'Signal Delete on adword and local'), (6, 'Signal Pause on adword and local'), (7, 'Signal Active on adword and local'), (8, 'STRATEGY KEYWORD SYNONMYS')], default=1, verbose_name='Publish state')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
            },
        ),
        migrations.CreateModel(
            name='JunctionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('state', models.SmallIntegerField(choices=[(-1, 'Deleted'), (0, 'Paused'), (1, 'Active'), (2, 'For Review'), (3, 'Expired'), (4, 'Cancelled'), (5, 'Signal Delete on adword and local'), (6, 'Signal Pause on adword and local'), (7, 'Signal Active on adword and local'), (8, 'STRATEGY KEYWORD SYNONMYS')], default=1, verbose_name='Publish state')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='junction_table_document', to='document_storage.digitaldocuments')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='junction_table_folder', to='document_storage.folder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('state', models.SmallIntegerField(choices=[(-1, 'Deleted'), (0, 'Paused'), (1, 'Active'), (2, 'For Review'), (3, 'Expired'), (4, 'Cancelled'), (5, 'Signal Delete on adword and local'), (6, 'Signal Pause on adword and local'), (7, 'Signal Active on adword and local'), (8, 'STRATEGY KEYWORD SYNONMYS')], default=1, verbose_name='Publish state')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('short_form_descriptors', models.CharField(blank=True, max_length=50, null=True)),
                ('long_form_descriptors', models.CharField(blank=True, max_length=50, null=True)),
                ('document', models.ManyToManyField(blank=True, null=True, related_name='topic_documents', through='document_storage.JunctionTable', to='document_storage.DigitalDocuments')),
                ('folder', models.ManyToManyField(blank=True, null=True, related_name='topic_folder', through='document_storage.JunctionTable', to='document_storage.Folder')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.AddField(
            model_name='junctiontable',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='junction_table_topic', to='document_storage.topics'),
        ),
        migrations.AddField(
            model_name='digitaldocuments',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_documents_folder', to='document_storage.folder'),
        ),
    ]
