# Generated by Django 4.0.1 on 2022-01-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='document',
        ),
        migrations.AddField(
            model_name='topics',
            name='document',
            field=models.ManyToManyField(blank=True, null=True, related_name='topic_documents', to='document_storage.DigitalDocuments'),
        ),
        migrations.RemoveField(
            model_name='topics',
            name='folder',
        ),
        migrations.AddField(
            model_name='topics',
            name='folder',
            field=models.ManyToManyField(blank=True, null=True, related_name='topic_folder', to='document_storage.Folder'),
        ),
        migrations.DeleteModel(
            name='JunctionTable',
        ),
    ]
