# Generated by Django 4.0.1 on 2022-01-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_storage', '0002_alter_topics_document_alter_topics_folder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitaldocuments',
            name='state',
            field=models.SmallIntegerField(choices=[(-1, 'Deleted'), (1, 'Active')], default=1, verbose_name='Publish state'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='state',
            field=models.SmallIntegerField(choices=[(-1, 'Deleted'), (1, 'Active')], default=1, verbose_name='Publish state'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='state',
            field=models.SmallIntegerField(choices=[(-1, 'Deleted'), (1, 'Active')], default=1, verbose_name='Publish state'),
        ),
    ]
