# Generated by Django 4.0.1 on 2022-01-12 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_storage', '0003_alter_digitaldocuments_state_alter_folder_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='document',
        ),
        migrations.AddField(
            model_name='topics',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_documents', to='document_storage.digitaldocuments'),
        ),
        migrations.RemoveField(
            model_name='topics',
            name='folder',
        ),
        migrations.AddField(
            model_name='topics',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_folder', to='document_storage.folder'),
        ),
    ]
