# Generated by Django 4.0.1 on 2022-01-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_storage', '0004_remove_topics_document_topics_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='long_form_descriptors',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='topics',
            name='short_form_descriptors',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
